### PR TITLE
Support millisecond intervals

### PR DESCRIPTION
**Pull request by judahrand**
This is pretty straightforward and allows sub-second intervals to be specified like any other. Mostly type hinting changes.

Closes: #75

### CODE REVIEW

**Comment by judahrand** [comment]
@vutran1710 This seems like a CI issue rather than a problem with my changes?

**Comment by JWCook** [comment]
Yeah, that appears to be an issue with poetry 1.2 dropping support for python 3.6:
https://github.com/snok/install-poetry/issues/89

That doesn't have anything to do with your changes, but the solution would be to either revert to poetry 1.1, or drop support for python 3.6.

**Comment by vutran1710** [comment]
@judahrand  you are gonna need to bump your version

**Comment by judahrand** [comment]
> @judahrand you are gonna need to bump your version

This should be find now given that it was updated on `master` with the Python 3.6 drop?

**Comment by judahrand** [comment]
@JWCook CI still seems broken?

**Comment by JWCook** [comment]
Hmm, the master branch [build succeeded](https://github.com/vutran1710/PyrateLimiter/actions/runs/3118888912), and this looks like a different error:
```
/home/runner/work/PyrateLimiter/PyrateLimiter/.venv/bin/python: bad interpreter: No such file or directory
```

Somehow the virtualenv's interpreter is missing? I don't think I've seen that one before. It must be a problem with the GitHub Actions cache. The cache key is defined here: https://github.com/vutran1710/PyrateLimiter/blob/ca1a54bba8efd6806c88c2f2ed6f759dce4b9374/.github/workflows/poetry-package.yml#L39

Probably the easiest way to invalidate it is to run `poetry update` and commit the changes. That will give `poetry.lock` a different hash, which will create a different cache key, which will cause the next CI run to create a new virtualenv instead of using the cached virtualenv.

**Comment by judahrand** [comment]
@JWCook That's sorted it!

**Comment by judahrand** [comment]
@JWCook This did pass all the tests...

There's definitely something funky with the CI on this project...

**Comment by JWCook** [comment]
Yeah, the tests all passed at least once, so this should be fine to merge.

@vutran1710 It seems like the build is now failing whenever it uses a cached virtualenv, which is something I haven't seen before. Unless you happen to know what's wrong there, it might be best just to disable the cache for now?

**Comment by vutran1710** [comment]
> > @judahrand you need to bump version in pyproject.toml and resolve the conflicts
> 
> Are you saying you want a minor version bump?
> 
> It strikes me as super weird that this is decided/managed by the contributors rather than part of the release process or managed automatically with a semver tool (and still determined at release time).

Yes, it should be automatically using some semver tool (I created an issuse for that), but have yet have time to implement it, thats why manual work is still needed for now. sorry for the inconvenience.

**Comment by JWCook** [comment]
#79 is at least a temporary fix for the cache issue encountered here.

> Yes, it should be automatically using some semver tool (I created an issuse for that), but have yet have time to implement it

Meanwhile, another option to consider is releasing only on git tags instead of on every push to `master`. That makes it easier to bundle multiple PRs into one release, or skip releases for minor things like config changes.

**Comment by judahrand** [comment]
> #79 is at least a temporary fix for the cache issue encountered here.
> 
> > Yes, it should be automatically using some semver tool (I created an issuse for that), but have yet have time to implement it
> 
> Meanwhile, another option to consider is releasing only on git tags instead of on every push to `master`. That makes it easier to bundle multiple PRs into one release, or skip releases for minor things like config changes.

Honestly, this is way more sensible imo

**Comment by JWCook** [comment]
Alright, can you rebase onto `master` again, and update the version once more to `2.8.3`? Hopefully that's the last thing.

**Comment by vutran1710** [comment]
No activity

**Comment by judahrand** [comment]
You don't want to add that single commit/rebase yourself and merge? Or leave it open and give me the opportunity to get back to it?!

Rude.

**Pull request closed without merging**
