### PR TITLE
Use floats instead of ints for calculating remaining_time

### LINKED ISSUE #40: Take into account time elapsed during calls
Hello,

It seems this library sleeps "duration" amount of time no matter how long the calls take.

See this example:

```python
import datetime
import time

from pyrate_limiter import Duration, Limiter, MemoryQueueBucket, RequestRate

limiter = Limiter(RequestRate(15, Duration.SECOND), bucket_class=MemoryQueueBucket)


@limiter.ratelimit("get_transfers", delay=True)
def hey(counter):
    time.sleep(0.01)
    print(datetime.datetime.now(), counter)


if __name__ == "__main__":
    for i in range(15):
        hey(i)

    for i in range(15):
        hey(i)

    for i in range(15):
        hey(i)
```

The output shows:

```
2021-09-21 20:43:14.531809 0
2021-09-21 20:43:14.542202 1
2021-09-21 20:43:14.552524 2
2021-09-21 20:43:14.562810 3
2021-09-21 20:43:14.573070 4
2021-09-21 20:43:14.583382 5
2021-09-21 20:43:14.593741 6
2021-09-21 20:43:14.604055 7
2021-09-21 20:43:14.614501 8
2021-09-21 20:43:14.624727 9
2021-09-21 20:43:14.635107 10
2021-09-21 20:43:14.645440 11
2021-09-21 20:43:14.655796 12
2021-09-21 20:43:14.666227 13
2021-09-21 20:43:14.676648 14
{'error': 'Bucket for get_transfers with Rate 15/1 is already full', 'identity': 'get_transfers', 'rate': '15/1', 'remaining_time': 1}
Rate limit reached; 1 seconds remaining before next request
2021-09-21 20:43:15.688529 0
2021-09-21 20:43:15.698823 1
2021-09-21 20:43:15.709181 2
2021-09-21 20:43:15.719494 3
2021-09-21 20:43:15.729820 4
2021-09-21 20:43:15.740170 5
2021-09-21 20:43:15.750634 6
2021-09-21 20:43:15.760945 7
2021-09-21 20:43:15.771326 8
2021-09-21 20:43:15.781699 9
2021-09-21 20:43:15.792020 10
2021-09-21 20:43:15.802379 11
2021-09-21 20:43:15.812845 12
2021-09-21 20:43:15.823293 13
2021-09-21 20:43:15.833631 14
{'error': 'Bucket for get_transfers with Rate 15/1 is already full', 'identity': 'get_transfers', 'rate': '15/1', 'remaining_time': 1}
Rate limit reached; 1 seconds remaining before next request
2021-09-21 20:43:16.845334 0
2021-09-21 20:43:16.855676 1
2021-09-21 20:43:16.866223 2
2021-09-21 20:43:16.876586 3
2021-09-21 20:43:16.886921 4
2021-09-21 20:43:16.897270 5
2021-09-21 20:43:16.907618 6
2021-09-21 20:43:16.917932 7
2021-09-21 20:43:16.928241 8
2021-09-21 20:43:16.938601 9
2021-09-21 20:43:16.949142 10
2021-09-21 20:43:16.959737 11
2021-09-21 20:43:16.970079 12
2021-09-21 20:43:16.980392 13
2021-09-21 20:43:16.990715 14
```

I expect the sleep to be (1 - (0.01*15)) seconds (which is around 0.85) but it actually just sleeps 1s instead. 

Am I understanding things correctly?

Thanks!

### PR DESCRIPTION
**Pull request by JWCook**
* Fixes #40 by using floats instead of ints for calculating `remaining_time`, to handle delays more granular than 1 second
* Add a test for this
* Use `time.monotonic()` instead of `time.time()` for the reasons mentioned in #36
* Bump version number
* Update lockfile with `poetry update`

### CODE REVIEW

**Comment by yawhide** [comment]
i noticed the changelog is a bit out of date. could I request this PR description to be placed in a changelog as well?

**Comment by vutran1710** [comment]
> i noticed the changelog is a bit out of date. could I request this PR description to be placed in a changelog as well?

Yeah, it has been quite outdated. I will update it.

**Comment by yawhide** [comment]
> > i noticed the changelog is a bit out of date. could I request this PR description to be placed in a changelog as well?
> 
> Yeah, it has been quite outdated. @JWCook can you update it?

Awesome 😎

**Comment by JWCook** [comment]
Done! I added changelog details for releases starting from 2.2.0.

**Comment by vutran1710** [comment]
Tks a lot man

**Pull request merged**
