### PR TITLE
Add a ratelimit decorator with async support

### LINKED ISSUE #21: Feature request/PR proposal: Add async support
Hi again, I was wondering if you would be open to the idea of adding async support to pyrate-limiter? If so, I'd be willing to put together a PR for this.

The basic idea would be the same as [this unmerged PR](https://github.com/tomasbasham/ratelimit/pull/35) for the abandoned [ratelimit](https://github.com/tomasbasham/ratelimit) repo:
* Add a decorator that calls `Limiter.try_acquire()` before calling the wrapped function
* Inspect the wrapped function to see if it's a coroutine, and if so return an async function; otherwise return a normal function

I have use cases for both synchronous and asynchronous rate-limiting in different projects. I did take a look at [aiolimiter](https://github.com/mjpieters/aiolimiter), but it would be handy if I could use pyrate-limiter for both cases!

### PR DESCRIPTION
**Pull request by JWCook**
Closes #21 

This PR adds a decorator, `Limiter.ratelimit`, that does the following:
* Works on both normal and async functions
* With no other arguments, raises `BucketFullException` when the rate limit is exceeded, as usual
* With `delay` argument, sleeps the appropriate amount of time until the next request
* With `delay` and `max_delay` argument, only sleeps if the delay time is <= `max_delay`, otherwise raises an exception

Dependency changes:
* Add `pytest-asyncio` to dev dependencies for running async tests
* Bump `pytest` version to `^5.4` (required by `pytest-asyncio`)
* Update lockfile

### CODE REVIEW

**Comment by JWCook** [comment]
@vutran1710 This is mostly done, let me know what you think so far.

The only issue remaining is the code complexity score from Code Climate. I'm not quite sure yet how to get that down to a 5 (currently 7).

**Comment by vutran1710** [comment]
codeclimate is not much of a big deal. The PR LGTM.

**Comment by vutran1710** [comment]
just a little note: can you move the examples in the ratelimit decorator to README?

**Comment by JWCook** [comment]
Done! Feel free to edit that if you can think of a better way to phrase those sections in the Readme.

**Comment by vutran1710** [comment]
All cool now. Tks!

**Pull request merged**
