### PR TITLE
More eyes, prolly less bugs.

### PR DESCRIPTION
**Pull request by amirouche**

### CODE REVIEW

**Comment by amirouche** [comment]
I added a few comments in https://github.com/vutran1710/PyrateLimiter/pull/36/commits/c0f99b9cfd4817a10d567c8120e83424abe3fb1f.

**Comment by amirouche** [comment]
Re the timer that is slow. What is required is to compute a precise delta, so in synchronous code `time.monotonic` is warranted, and in asynchronous `loop.time()` is a better fit. Also, `time.time` will move because leap seconds, daylight saving, so it might break the algorithm.

**Comment by amirouche** [comment]
Last but not least, I think the leaky bucket algorithm should be in my opinion synchronous, but may be asynchronous, when it is shared among several process and rely on REDIS. In anycase, it should be very clear how the algorithm works and is the primary source of interest in pyrate-limiter. The algorithm should be tested precisely and alone, before / without  the user usability matter (aka. public interface).

**Comment by vutran1710** [comment]
@amirouche first of all, thank you for the contribution.

I know that it's my fault I never setup an official contributing guideline, but I still expect to see something I can understand without any guessing. And to achieve that, I hope you can clarify a few things for me as following:

- This PR is for bug-fix /  improvement, or simply refactoring? Have a summary on the matter in the PR description.
- I read your PR and see some comments that start with things like `R0`, `R1` etc - which is something I'm not familiar with. Is this a convention? Is this a NOTE? Is this a TODO? etc. I'm afraid that my knowledge is limited and I'm not aware of this, but since this repo is a public repository, please use some plain English so other people can look at it without being scared away.
- I read your PR and see lots of changes both in code and in README. But apparently you only reformat the README with more line-breaks and all. If that's the case (refactoring), please state that in the PR. If there are both refactoring & improving part in the PR, please break the PR into 2 different PRs.
- A Pull request that is merged will result in CICD pipeline running. If you want to release a new version, please follow the Semantic Version convention and update the version using `poetry` in your PR.
- Regarding the timer correctness. I'd love to have an example, if you can provide one. That would be enlightening.
- Regarding the algorithm, I agree with you. Will see to update it in a near future.

Thanks and have a nice day.

**Comment by amirouche** [comment]
I did that PR after reviewing the code. Most of it is cosmit (to get into the codebase), and the gist of the review is in https://github.com/vutran1710/PyrateLimiter/pull/36/commits/c0f99b9cfd4817a10d567c8120e83424abe3fb1f

> * Regarding the timer correctness. I'd love to have an example, if you can provide one. That would be enlightening.

Sorry, that is the best I can do at the moment.

> * Regarding the algorithm, I agree with you. Will see to update it in a near future.

Good luck :100:

**Comment by JWCook** [comment]
@vutran1710 I think the point about using monotonic time in `Limiter.try_acquire()` is valid, and that would be a quick and easy change.

As for async code, [`loop.time()` just returns `time.monotonic()`](https://github.com/python/cpython/blob/96346cb6d0593ef9ec122614347ccb053cd63433/Lib/asyncio/base_events.py#L688-L695), so I don't think any special logic is required there.

> I think the leaky bucket algorithm should be in my opinion synchronous, but may be asynchronous, when it is shared among several process and rely on REDIS

@amirouche Can you elaborate on that? Are you talking about python `asyncio` specifically, or concurrency in a more general sense (multithreading, multiprocess, etc.)? Which specific parts are you concerned about not being async-safe, thread-safe, and/or multiprocess-safe?

**Comment by amirouche** [comment]
> @vutran1710 I think the point about using monotonic time in `Limiter.try_acquire()` is valid, and that would be a quick and easy change.
> 
> As for async code, [`loop.time()` just returns `time.monotonic()`](https://github.com/python/cpython/blob/96346cb6d0593ef9ec122614347ccb053cd63433/Lib/asyncio/base_events.py#L688-L695), so I don't think any special logic is required there.
> 

Oh! I was under the impression that this was cached per event-loop iteration; nevermind.

> > I think the leaky bucket algorithm should be in my opinion synchronous, but may be asynchronous, when it is shared among several process and rely on REDIS
> 
> @amirouche Can you elaborate on that? Are you talking about python `asyncio` specifically, or concurrency in a more general sense (multithreading, multiprocess, etc.)? Which specific parts are you concerned about not being async-safe, thread-safe, and/or multiprocess-safe?

It is my nerdview into getting maximum performance. At this time, trying to hit wikipedia as fast as possible with a single processus, a single thread and multiple workers, I can't go beyond 100 RPS, the limit being 200 RPS, that means one request every 5 milliseconds. Basically, I try to keep the hot path as performant as possible, and having the rate limiter async and using REDIS is getting a the way, even if prolly in a small way.

Here is the relevant code: https://github.com/amirouche/python-sourcery/blob/4c4f8f68e8fef4beee1b00e6b93f4f90be991b25/sourcery.py#L157-L180

Increasing the number of workers 200 at the moment, does not speed up the scraper.

Sorry, I got into my projects problems to give more background about what I am trying to achieve.

**Comment by amirouche** [comment]
(fwiw, the rate limiter may need to be adjusted during the crawl at runtime)

**Comment by JWCook** [comment]
Oh, interesting! Like vutran1710 I was a bit confused by this PR, but after seeing your example this makes more sense.

Would you like to open an issue for this instead of a PR, and just focus on algorithm performance and benchmarks? I think this would be a helpful use case for this library. Personally my use cases so far have been the opposite: using rate-limiting for slow sites, like 1-5 requests per second. If we're talking about hundreds of requests per second, there are a lot more issues to consider, like you noted.

Have you considered using [PyPy3](https://doc.pypy.org/en/latest/index.html) or another python implementation instead of CPython? Your 'hot path' here is something I think a JIT compiler would be a good fit for. Check out these benchmarks for example: https://morepypy.blogspot.com/2017/03/async-http-benchmarks-on-pypy3.html Ideally you should be able to push thousands of requests per second, at which point you'll actually need a rate-limiter to stay under 200, and then we can see if pyrate-limiter is a bottleneck or not.

I don't think pyrate-limiter has been tested with PyPy (only CPython so far), but that's something I'd be willing to help look into.

**Comment by amirouche** [comment]
I retried with stable pypy3, here is the stacktrace I have:

```python
	Exception ignored in: weakref callback <function WeakKeyDictionary.__init__.<locals>.remove at 0x00007fdf2e6e8f20>
Traceback (most recent call last):
  File "/usr/lib/pypy3/lib-python/3/weakref.py", line 390, in remove
    del self.data[k]
KeyError: <weakref at 0x00007fdf2dd1d340; dead>
Exception ignored in: weakref callback <function WeakKeyDictionary.__init__.<locals>.remove at 0x00007fdf2e6e8f20>
Traceback (most recent call last):
  File "/usr/lib/pypy3/lib-python/3/weakref.py", line 390, in remove
    del self.data[k]
KeyError: <weakref at 0x00007fdf2dd1d380; dead>
```

**Comment by amirouche** [comment]
Anyway, I come around in the issues of this project If can find something interesting _related_ to pyratelimiter (awesome name btw).

**Pull request closed without merging**
